using Microsoft.EntityFrameworkCore;
using WanderXServer.DataAccessLayer;
using WanderXServer.Dtos.Dashboard;
namespace WanderXServer.Services;
public sealed class DashboardService {
 private readonly WanderXDbContext _db; public DashboardService(WanderXDbContext db)=>_db=db;
 private static (DateTime From,DateTime To) Range(DashboardQuery q){ var now=DateTime.UtcNow.AddHours(7); var from=(q.FromDate??new DateTime(now.Year,now.Month,1)).Date; var to=(q.ToDate??from.AddMonths(1).AddDays(-1)).Date; if(from>to)throw new ArgumentException("FromDate must be before ToDate."); if(to>=from.AddMonths(12))throw new ArgumentException("Dashboard range cannot exceed 12 months."); return(from,to.AddDays(1)); }
 public async Task<DashboardSummary> Summary(DashboardQuery q){var r=Range(q);var bookings=Filter(_db.Bookings.AsNoTracking(),q).Where(x=>x.CreatedAt>=r.From&&x.CreatedAt<r.To);var revenue=bookings.Where(x=>x.Status=="Confirmed"||x.Status=="Finished");var today=DateTime.UtcNow.Date;var codes=await _db.GuideTourAssignments.AsNoTracking().Where(x=>x.StartDate>=today&&(x.Status=="Assigned"||x.Status=="Confirmed")).Select(x=>x.TourCode).Distinct().ToListAsync();var open=await _db.Tours.AsNoTracking().CountAsync(x=>(x.Status=="Published"||x.Status=="Open"||x.Status=="Active")&&x.Capacity>0&&codes.Contains(x.Code));var expected=await revenue.SumAsync(x=>(decimal?)x.TotalAmount)??0;var collected=await revenue.SumAsync(x=>(decimal?)(x.PaidAmount??0))??0;return new(){FromDate=r.From,ToDate=r.To.AddDays(-1),LastUpdated=DateTime.UtcNow,OpenTourCount=open,BookingCount=await bookings.CountAsync(),ExpectedRevenue=expected,CollectedRevenue=collected,OutstandingRevenue=Math.Max(0,expected-collected)};}
 public async Task<List<BookingStatusPoint>> Bookings(DashboardQuery q){var r=Range(q);return await Filter(_db.Bookings.AsNoTracking(),q).Where(x=>x.CreatedAt>=r.From&&x.CreatedAt<r.To).GroupBy(x=>new{x.CreatedAt.Date,x.Status}).Select(g=>new BookingStatusPoint{Date=g.Key.Date,Status=g.Key.Status,Count=g.Count()}).OrderBy(x=>x.Date).ThenBy(x=>x.Status).ToListAsync();}
 public async Task<RevenueByTourPage> Revenue(DashboardQuery q){var r=Range(q);var rows=await Filter(_db.Bookings.AsNoTracking(),q).Where(x=>x.CreatedAt>=r.From&&x.CreatedAt<r.To&&(x.Status=="Confirmed"||x.Status=="Finished")).GroupBy(x=>new{x.TourCode,x.TourName}).Select(g=>new RevenueByTourItem{TourCode=g.Key.TourCode??"N/A",TourName=g.Key.TourName,Expected=g.Sum(x=>x.TotalAmount),Collected=g.Sum(x=>x.PaidAmount??0)}).ToListAsync();foreach(var x in rows)x.Outstanding=Math.Max(0,x.Expected-x.Collected);var ordered=rows.OrderByDescending(x=>x.Expected).ThenBy(x=>x.TourCode).ToList();return new(){Page=q.Page,PageSize=q.PageSize,TotalCount=ordered.Count,TotalExpected=ordered.Sum(x=>x.Expected),TotalCollected=ordered.Sum(x=>x.Collected),Items=ordered.Skip((q.Page-1)*q.PageSize).Take(q.PageSize).ToList()};}
 public async Task<List<TopGuideItem>> Guides(DashboardQuery q){var r=Range(q);var assignments=await _db.GuideTourAssignments.AsNoTracking().Include(x=>x.GuideProfile).ThenInclude(x=>x.User).Where(x=>x.StartDate>=r.From&&x.StartDate<r.To).ToListAsync();var finished=assignments.Where(x=>x.Status.Equals("Finished",StringComparison.OrdinalIgnoreCase)).ToList();var codes=finished.Select(x=>x.TourCode).Distinct().ToList();var reviews=await(from v in _db.TourReviews.AsNoTracking() join b in _db.Bookings.AsNoTracking() on v.BookingId equals b.Id where v.Status=="Visible"&&b.TourCode!=null&&codes.Contains(b.TourCode) select new{b.TourCode,v.Rating}).ToListAsync();var groups=finished.GroupBy(x=>x.GuideProfileId).ToList();var max=Math.Max(1,groups.Select(g=>g.Count()).DefaultIfEmpty(1).Max());var list=new List<TopGuideItem>();foreach(var g in groups){var all=assignments.Where(x=>x.GuideProfileId==g.Key).ToList();var accepted=all.Count(x=>!x.Status.Equals("Declined",StringComparison.OrdinalIgnoreCase));var rs=reviews.Where(v=>g.Any(a=>a.TourCode==v.TourCode)).ToList();var completion=g.Count()/(double)max*40;var acceptance=all.Count==0?0:accepted/(double)all.Count*15;var rating=rs.Count==0?0:rs.Average(x=>x.Rating)/5d*30;var p=g.First().GuideProfile;list.Add(new(){GuideId=g.Key,GuideName=p.User.FullName,CompletedTours=g.Count(),AverageRating=rs.Count==0?null:rs.Average(x=>x.Rating),ReviewCount=rs.Count,AcceptanceRate=all.Count==0?0:accepted*100d/all.Count,Score=Math.Round(completion+acceptance+rating,2),RatingNote=rs.Count==0?"Chưa đủ mẫu":"Đủ dữ liệu",ScoreBreakdown=new(){$"Tour hoàn thành: {completion:0.0}/40",$"Đánh giá: {rating:0.0}/30",$"Nhận phân công: {acceptance:0.0}/15"}});}return list.OrderByDescending(x=>x.Score).ThenByDescending(x=>x.CompletedTours).ThenBy(x=>x.GuideId).Select((x,i)=>{x.Rank=i+1;return x;}).ToList();}
 private static IQueryable<WanderXServer.BusinessObject.Booking> Filter(IQueryable<WanderXServer.BusinessObject.Booking> x,DashboardQuery q){if(!string.IsNullOrWhiteSpace(q.TourCode))x=x.Where(b=>b.TourCode==q.TourCode);if(!string.IsNullOrWhiteSpace(q.Destination))x=x.Where(b=>b.Destination.Contains(q.Destination));if(!string.IsNullOrWhiteSpace(q.Status))x=x.Where(b=>b.Status==q.Status);return x;}
}