using System.Text.Json;using Microsoft.AspNetCore.DataProtection;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.WebUtilities;using WanderXServer.Services;
namespace WanderXServer.Controllers;
[ApiController,Route("api/auth/google")]
public sealed class GoogleAuthController:ControllerBase{
 private readonly IConfiguration _cfg;private readonly IHttpClientFactory _http;private readonly IDataProtector _protector;private readonly IAuthService _auth;
 public GoogleAuthController(IConfiguration cfg,IHttpClientFactory http,IDataProtectionProvider dp,IAuthService auth){_cfg=cfg;_http=http;_protector=dp.CreateProtector("WanderX.GoogleOAuth.State.v1");_auth=auth;}
 [HttpGet("start")]
 public IActionResult Start([FromQuery]string? returnUrl="/"){var clientId=_cfg["Authentication:Google:ClientId"];if(string.IsNullOrWhiteSpace(clientId))return Redirect(ClientError("GOOGLE_NOT_CONFIGURED"));var callback=_cfg["Authentication:Google:CallbackUrl"]??$"{Request.Scheme}://{Request.Host}/api/auth/google/callback";var safe=SafeReturn(returnUrl);var state=_protector.Protect(JsonSerializer.Serialize(new OAuthState(DateTimeOffset.UtcNow.ToUnixTimeSeconds(),safe)));var url=QueryHelpers.AddQueryString("https://accounts.google.com/o/oauth2/v2/auth",new Dictionary<string,string?>{{"client_id",clientId},{"redirect_uri",callback},{"response_type","code"},{"scope","openid email profile"},{"state",state},{"prompt","select_account"}});return Redirect(url);}
 [HttpGet("callback")]
 public async Task<IActionResult> Callback([FromQuery]string? code,[FromQuery]string? state,[FromQuery]string? error){if(!string.IsNullOrWhiteSpace(error))return Redirect(ClientError("GOOGLE_ACCESS_DENIED"));if(string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(state))return Redirect(ClientError("GOOGLE_CALLBACK_INVALID"));OAuthState parsed;try{parsed=JsonSerializer.Deserialize<OAuthState>(_protector.Unprotect(state))!;}catch{return Redirect(ClientError("GOOGLE_STATE_INVALID"));}if(DateTimeOffset.UtcNow.ToUnixTimeSeconds()-parsed.CreatedAt>600)return Redirect(ClientError("GOOGLE_STATE_EXPIRED"));var clientId=_cfg["Authentication:Google:ClientId"];var secret=_cfg["Authentication:Google:ClientSecret"];var callback=_cfg["Authentication:Google:CallbackUrl"]??$"{Request.Scheme}://{Request.Host}/api/auth/google/callback";if(string.IsNullOrWhiteSpace(clientId)||string.IsNullOrWhiteSpace(secret))return Redirect(ClientError("GOOGLE_NOT_CONFIGURED"));var client=_http.CreateClient();var tokenResponse=await client.PostAsync("https://oauth2.googleapis.com/token",new FormUrlEncodedContent(new Dictionary<string,string>{{"code",code},{"client_id",clientId},{"client_secret",secret},{"redirect_uri",callback},{"grant_type","authorization_code"}}));if(!tokenResponse.IsSuccessStatusCode)return Redirect(ClientError("GOOGLE_TOKEN_EXCHANGE_FAILED"));using var tokenJson=JsonDocument.Parse(await tokenResponse.Content.ReadAsStringAsync());var accessToken=tokenJson.RootElement.GetProperty("access_token").GetString();client.DefaultRequestHeaders.Authorization=new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer",accessToken);var infoResponse=await client.GetAsync("https://openidconnect.googleapis.com/v1/userinfo");if(!infoResponse.IsSuccessStatusCode)return Redirect(ClientError("GOOGLE_PROFILE_FAILED"));using var info=JsonDocument.Parse(await infoResponse.Content.ReadAsStringAsync());var email=info.RootElement.GetProperty("email").GetString();var verified=info.RootElement.TryGetProperty("email_verified",out var ev)&&ev.GetBoolean();if(string.IsNullOrWhiteSpace(email)||!verified)return Redirect(ClientError("GOOGLE_EMAIL_NOT_VERIFIED"));var name=info.RootElement.TryGetProperty("name",out var nv)?nv.GetString()??email:email;try{var result=await _auth.GoogleLoginAsync(email,name);var payload=WebEncoders.Base64UrlEncode(JsonSerializer.SerializeToUtf8Bytes(result));return Redirect($"{ClientBase()}/auth/google-callback#result={payload}&returnUrl={Uri.EscapeDataString(parsed.ReturnUrl)}");}catch(InvalidOperationException ex){return Redirect(ClientError(ex.Message));}}
 private string ClientBase()=>(_cfg["Authentication:Google:ClientBaseUrl"]??"http://localhost:5196").TrimEnd('/');private string ClientError(string code)=>$"{ClientBase()}/login?googleError={Uri.EscapeDataString(code)}";private static string SafeReturn(string? value)=>!string.IsNullOrWhiteSpace(value)&&value.StartsWith('/')&&!value.StartsWith("//")?value:"/";private sealed record OAuthState(long CreatedAt,string ReturnUrl);
}