// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WanderXServer.DataAccessLayer;

#nullable disable

namespace WanderXServer.Migrations
{
    [DbContext(typeof(WanderXDbContext))]
    [Migration("20260711160401_AddUserSpecialRequestsTable")]
    partial class AddUserSpecialRequestsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WanderXServer.BusinessObject.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85c94e16-4303-95d4-be76-141669bbba55"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ad@ad.123",
                            FullName = "WanderX Admin",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "AD@AD.123",
                            PasswordHash = "AQAAAAIAAYagAAAAELzrmn2Fi3pxcdppGEVdb00CPy7ZOtDLYeXfrg88FWJWbMK/28PwuforR/4RIWlP7Q==",
                            PhoneNumber = "+10000000000",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("95fac87b-89ea-2fb1-3728-cc3ae139d5c1"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.guide@wanderx.com",
                            FullName = "Elena Rodriguez",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "ELENA.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBKQjHHnzneogfJsVcsdM7iSYqz9tq855YRGV5TzSXyWjCxT7393xStGZ9ri/RvqAw==",
                            PhoneNumber = "+34123456789",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("17dfb04d-c76b-2ca8-53dd-d046876722bb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kenji.guide@wanderx.com",
                            FullName = "Kenji Tanaka",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "KENJI.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIx8fgcdkvfrPjQGqd4m+e/zyRnqCDm1n9aGdbjgRC6VT4xEaIpmOzm+KidKGq38og==",
                            PhoneNumber = "+81312345678",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("291d83be-f690-836b-0bc7-9e09068249d5"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zara.guide@wanderx.com",
                            FullName = "Zara Nkosi",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "ZARA.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPOMnoXsNxOailOYY8xxRvy/jT4nYnCZDPasUpDpyjrJdpzVsqjVN3lOdxxnXZbtGA==",
                            PhoneNumber = "+27111234567",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d8f1c642-e5df-297c-4c2b-46474f46b966"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marcus.guide@wanderx.com",
                            FullName = "Marcus Vane",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "MARCUS.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENyf110svtBdb2W9lUDHy7xla7kdzqB+t76HCYvQWEvuvLvVaKRGgS9IX7WQpTchDQ==",
                            PhoneNumber = "+442012345678",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("50294718-b00a-5ade-e743-dd51703db16f"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "linh.guide@wanderx.com",
                            FullName = "Linh Pham",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "LINH.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM5tcmLUECAW8Fkb12tgwBK+DsxncZ9NSPUgcXb4ll5HMdHF6xGEiDUKKe3uXP9krg==",
                            PhoneNumber = "+84901234567",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("7e47509a-5539-f246-0ed1-f4c44503381e"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aisha.guide@wanderx.com",
                            FullName = "Aisha Rahman",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "AISHA.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFEkC10x7wbQNTZcVM/czNyzMuR7jkEkCYl8mKB7c9EiaH5mkg7bW8swiI6WU8L5hA==",
                            PhoneNumber = "+971501234567",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("1ce80d60-b399-5bed-4433-56519702ab4b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diego.guide@wanderx.com",
                            FullName = "Diego Silva",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "DIEGO.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAVj3bI5WVtwap25zXS7gAhazmhJnfJePiQkXHejfPN0u3d8Oxpx/4txbyh9AHeHCA==",
                            PhoneNumber = "+5511987654321",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f20871e7-c4a8-9a20-5868-413a053dbc7d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mira.guide@wanderx.com",
                            FullName = "Mira Novak",
                            IsEmailConfirmed = true,
                            IsPhoneConfirmed = true,
                            NormalizedEmail = "MIRA.GUIDE@WANDERX.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECMEwTj4fkIsc+GLAPjUEqgcMY8Sr0PpEzhcU5WtGScwc51vFKJ5aJeT+EGB/e5G8w==",
                            PhoneNumber = "+385911234567",
                            Role = 2
                        });
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.AuthVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionFailedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmationFailedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentFailedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestFailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.BookingPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingPassengers");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.GuideProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("CompletedTours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpertiseArea")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GuideProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6b68305-41c7-ecf1-b56f-85775e02b7f7"),
                            Bio = "Certified trekking leader for alpine and cultural routes.",
                            CompletedTours = 86,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "High-Altitude Trekking",
                            Languages = "Spanish, English, French",
                            Region = "Europe Alps",
                            Status = "On Tour",
                            UserId = new Guid("95fac87b-89ea-2fb1-3728-cc3ae139d5c1")
                        },
                        new
                        {
                            Id = new Guid("c12f1645-3d28-c152-5960-6c1e15958131"),
                            Bio = "Food historian specializing in private markets and seasonal dining.",
                            CompletedTours = 112,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "Culinary Arts",
                            Languages = "Japanese, English",
                            Region = "Kyoto and Kansai",
                            Status = "On Tour",
                            UserId = new Guid("17dfb04d-c76b-2ca8-53dd-d046876722bb")
                        },
                        new
                        {
                            Id = new Guid("7aa42825-68f1-e8cb-d48f-59fc348793b0"),
                            Bio = "Wildlife interpreter for conservation-first safari experiences.",
                            CompletedTours = 47,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "Safari Wildlife",
                            Languages = "English, French",
                            Region = "Southern Africa",
                            Status = "Active",
                            UserId = new Guid("291d83be-f690-836b-0bc7-9e09068249d5")
                        },
                        new
                        {
                            Id = new Guid("a6512362-9ce5-25b4-190c-ba15b81d6db3"),
                            Bio = "Museum-trained historian for heritage and architecture tours.",
                            CompletedTours = 154,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "European History",
                            Languages = "English, German",
                            Region = "Western Europe",
                            Status = "Unavailable",
                            UserId = new Guid("d8f1c642-e5df-297c-4c2b-46474f46b966")
                        },
                        new
                        {
                            Id = new Guid("b8675ef8-50e0-79b1-4a5f-4bbffdaef105"),
                            Bio = "Central Vietnam specialist for royal heritage, craft villages, and coastal food trails.",
                            CompletedTours = 63,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "Heritage Walks",
                            Languages = "Vietnamese, English, Korean",
                            Region = "Hue, Da Nang, Hoi An",
                            Status = "On Tour",
                            UserId = new Guid("50294718-b00a-5ade-e743-dd51703db16f")
                        },
                        new
                        {
                            Id = new Guid("371d8c63-9c8c-9c42-9baa-454e86047fc9"),
                            Bio = "Desert logistics guide focused on private family itineraries and soft-adventure routes.",
                            CompletedTours = 78,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "Desert Expeditions",
                            Languages = "English, French, Thai",
                            Region = "UAE and Oman",
                            Status = "Active",
                            UserId = new Guid("7e47509a-5539-f246-0ed1-f4c44503381e")
                        },
                        new
                        {
                            Id = new Guid("7d5aa862-058c-0a75-79b8-3b82115eddc2"),
                            Bio = "Eco-guide for rainforest conservation trips, river routes, and birding experiences.",
                            CompletedTours = 39,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "Rainforest Ecology",
                            Languages = "Spanish, English, Italian",
                            Region = "Amazon Basin",
                            Status = "Active",
                            UserId = new Guid("1ce80d60-b399-5bed-4433-56519702ab4b")
                        },
                        new
                        {
                            Id = new Guid("0fb26a69-2fb8-1da1-55a3-45e6198d3da8"),
                            Bio = "Sailing host and coastal culture guide for small-group Adriatic itineraries.",
                            CompletedTours = 91,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpertiseArea = "Island Sailing",
                            Languages = "English, German, Italian",
                            Region = "Adriatic Coast",
                            Status = "Unavailable",
                            UserId = new Guid("f20871e7-c4a8-9a20-5868-413a053dbc7d")
                        });
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.GuideTourAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuideProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItinerarySummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MeetingPoint")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TourCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("TravelerCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuideProfileId");

                    b.ToTable("GuideTourAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c700894-792b-e7b3-a034-d56ef3d05d26"),
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Zermatt, Switzerland",
                            EndDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("f6b68305-41c7-ecf1-b56f-85775e02b7f7"),
                            ItinerarySummary = "Lead a premium alpine photography route, coordinate sunrise viewpoints, and manage safety pacing.",
                            MeetingPoint = "Zermatt Station, north entrance",
                            Region = "Europe Alps",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-ALP-102",
                            TourName = "Swiss Alps Photography Trek",
                            TravelerCount = 8
                        },
                        new
                        {
                            Id = new Guid("19d7922e-1f39-7acc-d726-82b057ce6df8"),
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Venice, Italy",
                            EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("f6b68305-41c7-ecf1-b56f-85775e02b7f7"),
                            ItinerarySummary = "Private cultural walking tour with artisan workshop and evening cicchetti tasting.",
                            MeetingPoint = "Hotel Danieli lobby",
                            Region = "Northern Italy",
                            StartDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-VEN-214",
                            TourName = "Venice Hidden Canals",
                            TravelerCount = 6
                        },
                        new
                        {
                            Id = new Guid("2836fd79-806d-9a63-ecf7-02d8dcd5da82"),
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Rome, Italy",
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EvidenceImage = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2Y0ZjZmOCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEyMCIgcj0iNDUiIGZpbGw9IiNlOGY1ZTkiLz48cGF0aCBkPSJNMTg1LDEyMCBMMTk1LDEzMCBMMjE1LDExMCIgc3Ryb2tlPSIjMmU3ZDMyIiBzdHJva2Utd2lkdGg9IjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0ibm9uZSIvPjx0ZXh0IHg9IjIwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC1zdHlsZT0ibm9ybWFsIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzJjM2U1MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG91ciBFdmlkZW5jZSBQcm9vZjwvdGV4dD48dGV4dCB4PSIyMDAiIHk9IjIyNSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTUiIGZpbGw9IiM3ZjhjOGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldhbmRlclggVmVyaWZpZWQgRmluaXNoPC90ZXh0Pjwvc3ZnPg==",
                            FinishedAt = new DateTime(2026, 6, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("f6b68305-41c7-ecf1-b56f-85775e02b7f7"),
                            ItinerarySummary = "After-hours private landmarks route with gallery access, local host coordination, and supper transfer.",
                            MeetingPoint = "Piazza Navona fountain",
                            Region = "Central Italy",
                            StartDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finished",
                            TourCode = "WX-ROM-078",
                            TourName = "Rome After Hours",
                            TravelerCount = 4,
                            UpdatedAt = new DateTime(2026, 6, 1, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b8b6e387-e407-e999-6721-6f9ba108e64d"),
                            CreatedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Andorra la Vella, Andorra",
                            EndDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("f6b68305-41c7-ecf1-b56f-85775e02b7f7"),
                            ItinerarySummary = "Four-day mountain traverse with vehicle support, wellness stops, and daily route briefings.",
                            MeetingPoint = "Grand Plaza Hotel reception",
                            Region = "Europe Alps",
                            StartDate = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-PYR-441",
                            TourName = "Pyrenees Luxury Traverse",
                            TravelerCount = 9
                        },
                        new
                        {
                            Id = new Guid("46a779a8-d13d-1481-486f-f1714e8d7dc5"),
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Nara, Japan",
                            EndDate = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("c12f1645-3d28-c152-5960-6c1e15958131"),
                            ItinerarySummary = "Temple etiquette support, tea master coordination, and cultural storytelling across private shrine visits.",
                            MeetingPoint = "Kintetsu Nara Station east gate",
                            Region = "Kansai",
                            StartDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-NAR-504",
                            TourName = "Nara Temples and Tea",
                            TravelerCount = 7
                        },
                        new
                        {
                            Id = new Guid("26af094f-eb8b-837c-5ff2-36296adf47ea"),
                            CreatedAt = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Kyoto, Japan",
                            EndDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("c12f1645-3d28-c152-5960-6c1e15958131"),
                            ItinerarySummary = "Market orientation, tea ceremony coordination, and private kaiseki dining support.",
                            MeetingPoint = "Nishiki Market west gate",
                            Region = "Kyoto and Kansai",
                            StartDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-KYO-330",
                            TourName = "Kyoto Culinary Immersion",
                            TravelerCount = 10
                        },
                        new
                        {
                            Id = new Guid("679949fb-cd9d-effb-d009-8cee79678322"),
                            CreatedAt = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Osaka, Japan",
                            EndDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EvidenceImage = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2Y0ZjZmOCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEyMCIgcj0iNDUiIGZpbGw9IiNlOGY1ZTkiLz48cGF0aCBkPSJNMTg1LDEyMCBMMTk1LDEzMCBMMjE1LDExMCIgc3Ryb2tlPSIjMmU3ZDMyIiBzdHJva2Utd2lkdGg9IjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0ibm9uZSIvPjx0ZXh0IHg9IjIwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC1zdHlsZT0ibm9ybWFsIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzJjM2U1MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG91ciBFdmlkZW5jZSBQcm9vZjwvdGV4dD48dGV4dCB4PSIyMDAiIHk9IjIyNSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTUiIGZpbGw9IiM3ZjhjOGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldhbmRlclggVmVyaWZpZWQgRmluaXNoPC90ZXh0Pjwvc3ZnPg==",
                            FinishedAt = new DateTime(2026, 6, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("c12f1645-3d28-c152-5960-6c1e15958131"),
                            ItinerarySummary = "Hands-on takoyaki workshop, local bar crawl routing, and dietary preference support.",
                            MeetingPoint = "Namba Station exit 14",
                            Region = "Kansai",
                            StartDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finished",
                            TourCode = "WX-OSA-119",
                            TourName = "Osaka Street Food Lab",
                            TravelerCount = 12,
                            UpdatedAt = new DateTime(2026, 6, 9, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("baf5d3d5-ee11-72d3-ca31-c786b76a3197"),
                            CreatedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Tokyo, Japan",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("c12f1645-3d28-c152-5960-6c1e15958131"),
                            ItinerarySummary = "Architecture, fashion ateliers, and private design studio visits for a small creative group.",
                            MeetingPoint = "Aoyama Grand Hotel lobby",
                            Region = "Kanto",
                            StartDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-TOK-204",
                            TourName = "Tokyo Design Weekend",
                            TravelerCount = 5
                        },
                        new
                        {
                            Id = new Guid("08ff049e-b97b-7a33-f88d-6e6f3bb0fb85"),
                            CreatedAt = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Serengeti, Tanzania",
                            EndDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7aa42825-68f1-e8cb-d48f-59fc348793b0"),
                            ItinerarySummary = "Wildlife interpretation, conservation briefing, and daily field logistics for safari guests.",
                            MeetingPoint = "Arusha Coffee Lodge reception",
                            Region = "Southern Africa",
                            StartDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-SAF-718",
                            TourName = "Serengeti Conservation Safari",
                            TravelerCount = 12
                        },
                        new
                        {
                            Id = new Guid("2fa60f03-1a79-8a76-2b4f-0dae8853a701"),
                            CreatedAt = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Kruger National Park, South Africa",
                            EndDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7aa42825-68f1-e8cb-d48f-59fc348793b0"),
                            ItinerarySummary = "Morning game drives, track-reading sessions, and family-friendly conservation storytelling.",
                            MeetingPoint = "Skukuza Airport arrivals",
                            Region = "Southern Africa",
                            StartDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-KRU-635",
                            TourName = "Kruger Big Five Field Notes",
                            TravelerCount = 8
                        },
                        new
                        {
                            Id = new Guid("03590cb6-1594-8533-dbfa-0792e4d667e3"),
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Cape Town, South Africa",
                            EndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EvidenceImage = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2Y0ZjZmOCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEyMCIgcj0iNDUiIGZpbGw9IiNlOGY1ZTkiLz48cGF0aCBkPSJNMTg1LDEyMCBMMTk1LDEzMCBMMjE1LDExMCIgc3Ryb2tlPSIjMmU3ZDMyIiBzdHJva2Utd2lkdGg9IjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0ibm9uZSIvPjx0ZXh0IHg9IjIwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC1zdHlsZT0ibm9ybWFsIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzJjM2U1MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG91ciBFdmlkZW5jZSBQcm9vZjwvdGV4dD48dGV4dCB4PSIyMDAiIHk9IjIyNSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTUiIGZpbGw9IiM3ZjhjOGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldhbmRlclggVmVyaWZpZWQgRmluaXNoPC90ZXh0Pjwvc3ZnPg==",
                            FinishedAt = new DateTime(2026, 5, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7aa42825-68f1-e8cb-d48f-59fc348793b0"),
                            ItinerarySummary = "Penguin colony visit, marine ecology briefing, and coastal picnic coordination.",
                            MeetingPoint = "V&A Waterfront Clock Tower",
                            Region = "Southern Africa",
                            StartDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finished",
                            TourCode = "WX-CPT-088",
                            TourName = "Cape Town Coastal Wildlife",
                            TravelerCount = 6,
                            UpdatedAt = new DateTime(2026, 5, 25, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2756a29c-7607-ed22-fda9-318b100098a5"),
                            CreatedAt = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeclineReason = "Visa processing conflict with another cross-border assignment.",
                            DeclinedAt = new DateTime(2026, 7, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Livingstone, Zambia",
                            EndDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7aa42825-68f1-e8cb-d48f-59fc348793b0"),
                            ItinerarySummary = "River trail guiding, waterfall history, and sunset boat support.",
                            MeetingPoint = "Royal Livingstone Hotel veranda",
                            Region = "Southern Africa",
                            StartDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Declined",
                            TourCode = "WX-VIC-012",
                            TourName = "Victoria Falls River Walk",
                            TravelerCount = 10,
                            UpdatedAt = new DateTime(2026, 7, 3, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ee381434-dcf6-d2a8-4786-35274ffb2330"),
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeclineReason = "Guide unavailable for medical appointment.",
                            DeclinedAt = new DateTime(2026, 6, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "London, United Kingdom",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("a6512362-9ce5-25b4-190c-ba15b81d6db3"),
                            ItinerarySummary = "Curated museum access with architectural context and private dining transfer.",
                            MeetingPoint = "British Museum main entrance",
                            Region = "Western Europe",
                            StartDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Declined",
                            TourCode = "WX-LON-901",
                            TourName = "London Museum Privileges",
                            TravelerCount = 5,
                            UpdatedAt = new DateTime(2026, 6, 8, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11a5eaaa-9b23-40a1-adf0-38c8b62ed32d"),
                            CreatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Paris, France",
                            EndDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("a6512362-9ce5-25b4-190c-ba15b81d6db3"),
                            ItinerarySummary = "Private Belle Epoque architecture route with atelier visit and evening performance transfer.",
                            MeetingPoint = "Le Meurice lobby",
                            Region = "Western Europe",
                            StartDate = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-PAR-510",
                            TourName = "Paris Belle Epoque",
                            TravelerCount = 6
                        },
                        new
                        {
                            Id = new Guid("aa6a3c1e-ceb3-4263-a3cc-0888bebfb0b9"),
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Hue, Vietnam",
                            EndDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("b8675ef8-50e0-79b1-4a5f-4bbffdaef105"),
                            ItinerarySummary = "Imperial Citadel interpretation, dragon boat logistics, and royal cuisine experience coordination.",
                            MeetingPoint = "Azerai La Residence lobby",
                            Region = "Central Vietnam",
                            StartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-HUE-226",
                            TourName = "Hue Imperial Heritage",
                            TravelerCount = 9
                        },
                        new
                        {
                            Id = new Guid("cbcc468d-f978-02b4-ecbe-f76a0d5d17da"),
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Hoi An, Vietnam",
                            EndDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("b8675ef8-50e0-79b1-4a5f-4bbffdaef105"),
                            ItinerarySummary = "Old town craft route, lantern workshop translation, and riverside dinner support.",
                            MeetingPoint = "Japanese Covered Bridge",
                            Region = "Central Vietnam",
                            StartDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-HAN-315",
                            TourName = "Hoi An Lantern Makers",
                            TravelerCount = 5
                        },
                        new
                        {
                            Id = new Guid("6a9c12e1-7de2-c2dd-6b42-9f51fd57af6e"),
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Da Nang, Vietnam",
                            EndDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EvidenceImage = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2Y0ZjZmOCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEyMCIgcj0iNDUiIGZpbGw9IiNlOGY1ZTkiLz48cGF0aCBkPSJNMTg1LDEyMCBMMTk1LDEzMCBMMjE1LDExMCIgc3Ryb2tlPSIjMmU3ZDMyIiBzdHJva2Utd2lkdGg9IjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0ibm9uZSIvPjx0ZXh0IHg9IjIwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC1zdHlsZT0ibm9ybWFsIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzJjM2U1MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG91ciBFdmlkZW5jZSBQcm9vZjwvdGV4dD48dGV4dCB4PSIyMDAiIHk9IjIyNSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTUiIGZpbGw9IiM3ZjhjOGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldhbmRlclggVmVyaWZpZWQgRmluaXNoPC90ZXh0Pjwvc3ZnPg==",
                            FinishedAt = new DateTime(2026, 6, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("b8675ef8-50e0-79b1-4a5f-4bbffdaef105"),
                            ItinerarySummary = "Wellness-focused coastal route with spa transfers, seafood tasting, and sunrise photo stops.",
                            MeetingPoint = "InterContinental Sun Peninsula lobby",
                            Region = "Central Vietnam",
                            StartDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finished",
                            TourCode = "WX-DNG-144",
                            TourName = "Da Nang Coastal Wellness",
                            TravelerCount = 4,
                            UpdatedAt = new DateTime(2026, 6, 3, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("434cec88-3548-881f-0908-654c115c9c60"),
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Dubai, UAE",
                            EndDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("371d8c63-9c8c-9c42-9baa-454e86047fc9"),
                            ItinerarySummary = "Contemporary design route, private desert camp handoff, and family-friendly pacing.",
                            MeetingPoint = "Museum of the Future entrance",
                            Region = "UAE and Oman",
                            StartDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-DXB-618",
                            TourName = "Dubai Design and Desert",
                            TravelerCount = 7
                        },
                        new
                        {
                            Id = new Guid("3823c9c1-f34e-8b72-e025-ff01c6edcd13"),
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Muscat, Oman",
                            EndDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("371d8c63-9c8c-9c42-9baa-454e86047fc9"),
                            ItinerarySummary = "Coastal forts, souq interpretation, and frankincense workshop coordination.",
                            MeetingPoint = "Al Alam Palace parking court",
                            Region = "UAE and Oman",
                            StartDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-MCT-407",
                            TourName = "Muscat Forts and Frankincense",
                            TravelerCount = 6
                        },
                        new
                        {
                            Id = new Guid("10899a07-b207-8825-76b9-63e7dcf0562d"),
                            CreatedAt = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeclineReason = "Family emergency; requested reassignment before confirmation.",
                            DeclinedAt = new DateTime(2026, 6, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Abu Dhabi, UAE",
                            EndDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("371d8c63-9c8c-9c42-9baa-454e86047fc9"),
                            ItinerarySummary = "Cultural etiquette briefing and mosque architecture tour.",
                            MeetingPoint = "Grand Mosque visitor center",
                            Region = "UAE and Oman",
                            StartDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Declined",
                            TourCode = "WX-AUH-090",
                            TourName = "Abu Dhabi Grand Mosque Etiquette",
                            TravelerCount = 11,
                            UpdatedAt = new DateTime(2026, 6, 4, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("da8528f1-132b-0514-32cb-f2eef3cdbb27"),
                            CreatedAt = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Manaus, Brazil",
                            EndDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7d5aa862-058c-0a75-79b8-3b82115eddc2"),
                            ItinerarySummary = "Dawn birding route, canopy safety briefing, and lodge-to-river coordination.",
                            MeetingPoint = "Manaus river port pier 3",
                            Region = "Amazon Basin",
                            StartDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-AMZ-552",
                            TourName = "Amazon Dawn Birding",
                            TravelerCount = 6
                        },
                        new
                        {
                            Id = new Guid("d4662d14-7966-cab3-bfc8-f325bc15514b"),
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Cusco, Peru",
                            EndDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7d5aa862-058c-0a75-79b8-3b82115eddc2"),
                            ItinerarySummary = "Cloud forest ecology, lodge orientation, and daily trail difficulty checks.",
                            MeetingPoint = "Cusco airport domestic arrivals",
                            Region = "Amazon Basin",
                            StartDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TourCode = "WX-PER-662",
                            TourName = "Peruvian Cloud Forest",
                            TravelerCount = 8
                        },
                        new
                        {
                            Id = new Guid("810a2896-c7b3-b391-b934-390e0ac90d8b"),
                            CreatedAt = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Rio de Janeiro, Brazil",
                            EndDate = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            EvidenceImage = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2Y0ZjZmOCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEyMCIgcj0iNDUiIGZpbGw9IiNlOGY1ZTkiLz48cGF0aCBkPSJNMTg1LDEyMCBMMTk1LDEzMCBMMjE1LDExMCIgc3Ryb2tlPSIjMmU3ZDMyIiBzdHJva2Utd2lkdGg9IjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0ibm9uZSIvPjx0ZXh0IHg9IjIwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC1zdHlsZT0ibm9ybWFsIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzJjM2U1MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG91ciBFdmlkZW5jZSBQcm9vZjwvdGV4dD48dGV4dCB4PSIyMDAiIHk9IjIyNSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTUiIGZpbGw9IiM3ZjhjOGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldhbmRlclggVmVyaWZpZWQgRmluaXNoPC90ZXh0Pjwvc3ZnPg==",
                            FinishedAt = new DateTime(2026, 5, 27, 18, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("7d5aa862-058c-0a75-79b8-3b82115eddc2"),
                            ItinerarySummary = "Atlantic forest nature walk, viewpoint timing, and local lunch coordination.",
                            MeetingPoint = "Copacabana Palace entrance",
                            Region = "Brazil Coast",
                            StartDate = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finished",
                            TourCode = "WX-RIO-203",
                            TourName = "Rio Atlantic Forest Day",
                            TravelerCount = 5,
                            UpdatedAt = new DateTime(2026, 5, 27, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9550475c-e646-90fb-5550-500b9773f62b"),
                            CreatedAt = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Split, Croatia",
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("0fb26a69-2fb8-1da1-55a3-45e6198d3da8"),
                            ItinerarySummary = "Island-hopping route, marina coordination, swim-stop safety, and coastal storytelling.",
                            MeetingPoint = "Split marina gate B",
                            Region = "Adriatic Coast",
                            StartDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Assigned",
                            TourCode = "WX-ADR-884",
                            TourName = "Croatian Islands by Sail",
                            TravelerCount = 8
                        },
                        new
                        {
                            Id = new Guid("28287815-5d53-79f3-ef65-dc4049d0d165"),
                            CreatedAt = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Dubrovnik, Croatia",
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            EvidenceImage = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MDAiIGhlaWdodD0iMzAwIiB2aWV3Qm94PSIwIDAgNDAwIDMwMCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2Y0ZjZmOCIvPjxjaXJjbGUgY3g9IjIwMCIgY3k9IjEyMCIgcj0iNDUiIGZpbGw9IiNlOGY1ZTkiLz48cGF0aCBkPSJNMTg1LDEyMCBMMTk1LDEzMCBMMjE1LDExMCIgc3Ryb2tlPSIjMmU3ZDMyIiBzdHJva2Utd2lkdGg9IjYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0ibm9uZSIvPjx0ZXh0IHg9IjIwMCIgeT0iMjAwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgZm9udC1zaXplPSIxOCIgZm9udC1zdHlsZT0ibm9ybWFsIiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzJjM2U1MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+VG91ciBFdmlkZW5jZSBQcm9vZjwvdGV4dD48dGV4dCB4PSIyMDAiIHk9IjIyNSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTUiIGZpbGw9IiM3ZjhjOGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldhbmRlclggVmVyaWZpZWQgRmluaXNoPC90ZXh0Pjwvc3ZnPg==",
                            FinishedAt = new DateTime(2026, 6, 11, 18, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("0fb26a69-2fb8-1da1-55a3-45e6198d3da8"),
                            ItinerarySummary = "Early-access wall walk, filming-location context, and breakfast terrace transfer.",
                            MeetingPoint = "Pile Gate outer bridge",
                            Region = "Adriatic Coast",
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finished",
                            TourCode = "WX-DBV-733",
                            TourName = "Dubrovnik Walls at Sunrise",
                            TravelerCount = 4,
                            UpdatedAt = new DateTime(2026, 6, 11, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3355672a-fa40-0b58-208d-ac4a10788969"),
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeclineReason = "Boat captain schedule changed; guide requested operations review.",
                            DeclinedAt = new DateTime(2026, 6, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Destination = "Hvar, Croatia",
                            EndDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuideProfileId = new Guid("0fb26a69-2fb8-1da1-55a3-45e6198d3da8"),
                            ItinerarySummary = "Sailing day with vineyard visit and island dinner booking.",
                            MeetingPoint = "Hvar harbor customs pier",
                            Region = "Adriatic Coast",
                            StartDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Declined",
                            TourCode = "WX-HVR-520",
                            TourName = "Hvar Wine and Sail",
                            TravelerCount = 6,
                            UpdatedAt = new DateTime(2026, 6, 23, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.UserSpecialRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("UserSpecialRequests");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.AuthVerificationCode", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.ApplicationUser", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.Booking", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.BookingPassenger", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.GuideProfile", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.ApplicationUser", "User")
                        .WithOne("GuideProfile")
                        .HasForeignKey("WanderXServer.BusinessObject.GuideProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.GuideTourAssignment", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.GuideProfile", "GuideProfile")
                        .WithMany()
                        .HasForeignKey("GuideProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuideProfile");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.PasswordResetToken", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.ApplicationUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.UserSpecialRequest", b =>
                {
                    b.HasOne("WanderXServer.BusinessObject.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("GuideProfile");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("VerificationCodes");
                });

            modelBuilder.Entity("WanderXServer.BusinessObject.Booking", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
